# Generated by Django 3.1.8 on 2021-07-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.CharField(default=0.00046109993293091885, max_length=100),
            preserve_default=False,
        ),
    ]
